################################# Default configuration ###################
baseURL = "//pamelayoungjacobs.com"
title = "Pamela Young-Jacobs for Columbus County Board of Visitors"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

################################# Outputs #################################
# hugo outputs
[outputs]
home = ["HTML"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "115px"
# Meta data
description = "Pamela Young-Jacobs for Columbus County Board of Education"
author = "Pamela Young-Jacobs"
# Contact Information
#mobile = "0124857985320"
email = "jacobsforboe@gmail.com"
location = "Bolton, NC"
# contact form action
contact_form_action = "https://formspree.io/xeqpjzre" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-178061079-1" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
#[params.nav_button]
#enable = true
#label = "Get A Quote"
#link = "contact"

# google map
#[params.gmap]
#enable = true
#gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
#map_latitude = "51.5223477"
#map_longitude = "-0.1622023"
#map_marker = "images/marker.png"

  
############################# social site ########################
#[[params.social]]
#icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
#link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.linkedin.com/in/pamela-young-jacobs-bis-989b0a36/"

#[[params.social]]
#icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
#link = "#"

#[[params.social]]
#icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
#link = "#"

#[[params.social]]
#icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
#link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/PamelaYoungJacobsforCoCoBoE"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 Pamela Young-Jacobs All Rights Reserved"


######################### english navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About Me"
URL = "about"
weight = 2

[[Languages.en.menu.main]]
name = "Why I'm Running"
URL = "why-im-running"
weight = 3

#[[Languages.en.menu.main]]
#name = "Volunteer"
#URL = "service"
#weight = 4

[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 5


# footer menu
[[Languages.en.menu.footer]]
name = "About Me"
URL = "about"
weight = 1

[[Languages.en.menu.footer]]
name = "Why I'm Running"
URL = "why-im-running"
weight = 2

#[[Languages.en.menu.footer]]
#name = "Volunteer"
#URL = "service"
#weight = 3

[[Languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 4
